publickey: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAJSZc2o/TmlSCcIIwEBeG1gYLgQsKEKG83zwnzGg/Vk+pY8xKFuCfdWI8p2V0ly06I7+URG+MfUukX2+Y8rda4MCAwEAAQ==
spring:
  application:
    name: framework
  jpa:
    show-sql: true
    properties:
      hibernate:
        hbm2ddl:
          auto: none
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/butterfly?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: butterfly
      password: iinxWjaiXVRhnamyl1oonS1nYAv8ot62b6yMBrtftOkKbwL4T6xmTBJuyBFIK74C42NOZ/Oy9NcwwgK3HXhcmA==
      driver-class-name: com.mysql.jdbc.Driver
      # 初始化连接池 最小 最大数量
      initial-size: 1
      min-idle: 3
      max-active: 20
      # 获取连接最大等待时间
      max-wait: 60000
      # 间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 30000
      # 检查连接的SQL
      validation-query: select 'x'
      # 检查连接的场景
      test-on-return: false
      test-on-borrow: false
      test-while-idle: true
      # 打开PSCache，并且指定每个连接上PSCache的大小 Oracle建议打开。Mysql建议关闭
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
      # 监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙(检测SQL注入)
      filters: stat,slf4j,config
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*'
      stat-view-servlet:
        enabled: true
        reset-enable: true
        allow: 127.0.0.1
        deny: 192.168.1.73
        login-username: admin
        login-password: admin
      filter:
        # 慢SQL监控
        stat:
          log-slow-sql: true
          slow-sql-millis: 3000
          merge-sql: true
        # 数据库密码加密
        config:
          enabled: true
      # 配置密码的公钥 默认使用druid的ConfigTool进行加密
      connection-properties: config.decrypt=true;config.decrypt.key=${publickey}
  mail:
    host: smtp.163.com
    username: 15260286656@163.com
    password: woaini1314
    from: 15260286656@163.com
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  # redis配置
  redis:
    # 默认的数据库分片
    database: 0
    host: localhost
    port: 6379
    password:
    default-expiration: 3000
    lettuce:
      pool:
        #最大active的连接
        max-active: 8
        # 最大空闲数和最小空闲数
        min-idle: 0
        max-idle: 8
        # 连接池最大阻塞等待时间 -1表示没有限制
        max-wait: -1
    # 连接超时时间 单位毫秒
    timeout: 30000
  #数据库版本管理
  liquibase:
    #changelog所在的位置。
    change-log: classpath:db/changelog/db.changelog-master.yaml
    #是否启动liqubase
    enabled: true
    #每次都是否把表删除在处理
    drop-first: false
#设置server的基本信息
server:
  servlet:
    session:
      cookie:
        http-only: true
# actuator配置
show:
  swagger: true
log:
  path: /Users/apple/Documents/newbiest/log
management:
  port: 9990
  address: 127.0.0.1
  security:
    enabled: false #敏感信息设置
    roles: ADMIN
  context-path: /manage
  info:
   build:
      enabled: true